[
  {
    id: 2,
    ranking: {
      myName: "우림",
      myRank: 32,
      prevName: "신동아2차",
      nextName: "더샵오산센트럴",
    },
    itemScore: {
      jeonsePercent: [92.0, 9],
      gapPrice: ["1.4천만원", 92],
      totalPrice: ["1395억", 45],
      flatPrice: ["7백만", 89],
    },
    priceInfo: {
      widthType: [
        {
          id: 1,
          households: 26,
          type: 12,
          supplyArea: 40,
          dedicatedArea: 28,
          sellingPrice: "8.4천만원",
          jeonsePrice: "1.2억원",
        },
        {
          id: 2,
          households: 4,
          type: 21,
          supplyArea: 67,
          dedicatedArea: 47,
          sellingPrice: "1억원",
          jeonsePrice: "1.3억원",
        },
        {
          id: 3,
          households: 113,
          type: 25,
          supplyArea: 82,
          dedicatedArea: 58,
          sellingPrice: "2.1억원",
          jeonsePrice: "1.7억원",
        },
        {
          id: 4,
          households: 1,
          type: 31,
          supplyArea: 102,
          dedicatedArea: 71,
          sellingPrice: "1.9억원",
          jeonsePrice: "1.6억원",
        },
        {
          id: 5,
          households: 13,
          type: 37,
          supplyArea: 123,
          dedicatedArea: 86,
          sellingPrice: "2.5억원",
          jeonsePrice: "1.6억원",
        },
      ],
    },
    saleInfo: [
      {
        id: 1,
        floor: "104동 1층",
        space: "110m²(33평)",
        date: "22.12.27",
        kind: "매매",
        price: 4,
      },
      {
        id: 2,
        floor: "104동 2층",
        space: "110m²(33평)",
        date: "22.12.27",
        kind: "매매",
        price: 3.8,
      },
      {
        id: 3,
        floor: "102동 10층",
        space: "110m²(33평)",
        date: "22.12.27",
        kind: "매매",
        price: 4,
      },
      {
        id: 4,
        floor: "104동 5층",
        space: "110m²(33평)",
        date: "22.12.27",
        kind: "매매",
        price: 3.8,
      },
      {
        id: 5,
        floor: "104동 1층",
        space: "110m²(33평)",
        date: "22.12.26",
        kind: "매매",
        price: 3.4,
      },
    ],
    basicInfo: {
      adress: "경기도 오산시 대원동 901",
      createDate: "2009년",
      households: "433세대 (총6개동)",
      ablePark: "1.45세대",
      heat: "지역난방, 열병합",
    },
  },
];
