export const widthDataType = [
  {
    id: 1,
    households: 26,
    type: 12,
    supplyArea: 40,
    dedicatedArea: 28,
    sellingPrice: "8.4천만원",
    jeonsePrice: "1.2억원",
  },
  {
    id: 2,
    households: 4,
    type: 21,
    supplyArea: 67,
    dedicatedArea: 47,
    sellingPrice: "1억원",
    jeonsePrice: "1.3억원",
  },
  {
    id: 3,
    households: 113,
    type: 25,
    supplyArea: 82,
    dedicatedArea: 58,
    sellingPrice: "2.1억원",
    jeonsePrice: "1.7억원",
  },
  {
    id: 4,
    households: 1,
    type: 31,
    supplyArea: 102,
    dedicatedArea: 71,
    sellingPrice: "1.9억원",
    jeonsePrice: "1.6억원",
  },
  {
    id: 5,
    households: 13,
    type: 37,
    supplyArea: 123,
    dedicatedArea: 86,
    sellingPrice: "2.5억원",
    jeonsePrice: "1.6억원",
  },
];
